/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Okna;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

import snitker.PierwszeFunkcje;

/**
 *
 * @author norbert
 */
public class WynikiOpisowe extends javax.swing.JFrame {

	/**
	 * Creates new form WynikiOpisowe3
	 */

	int iloscKolumn;
	private ArrayList<HistogramPrzedzialowy> histpAL = PierwszeFunkcje.getHistpAL();
	private ArrayList<Histogram> histAL = PierwszeFunkcje.getHistAL();

	public WynikiOpisowe() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Statystyki Opisowe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nazwa Pliku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(100, 100, 599, 586);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WynikiOpisowe.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WynikiOpisowe.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WynikiOpisowe.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WynikiOpisowe.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WynikiOpisowe().setVisible(true);
			}
		});
	}

	public void ustawjLabel1(String napis) {
		jLabel2.setText(napis);
	}

	public void ustawjEditorPane1(String tresc) {
		jEditorPane1.setText(tresc);
	}

	public void przyciski(String[] tytul) {
		int iloscKolumn = tytul.length;

		jPanel1.setLayout(new GridLayout(0, iloscKolumn)); // 0 - tworzy tyle
															// wierszy, ile
															// potrzeba

		for (int i = 0; i < iloscKolumn; i++) {
			TitledBorder titled = BorderFactory.createTitledBorder(tytul[i]);
			dodPanel(titled, tytul[i], i);

		}
		jPanel1.revalidate();
		jPanel1.repaint();
	}

	private void dodPanel(Border krawedz, final String zawartosc, final int kolumna) {
		JPanel malyPanel = new JPanel(new GridLayout(0, 1), false);
		JLabel label = new JLabel(" ", JLabel.CENTER);
		malyPanel.add(label);
		malyPanel.setBorder(krawedz);
		
		JButton przyciskH = new JButton();
		przyciskH.setText("Histogram");
		przyciskH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				przyciskHActionPerformed(evt, kolumna, zawartosc);
			}
		});
		malyPanel.add(przyciskH);
		
		
		JButton przyciskHP = new JButton();
		przyciskHP.setText("Histogram przedziałowy");
		przyciskHP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				przyciskHPActionPerformed(evt, kolumna, zawartosc);
			}
		});
		malyPanel.add(przyciskHP);
		
		
		JButton przyciskTestSeriiM1 = new JButton();
		przyciskTestSeriiM1.setText("Test serii [model 1]");
		przyciskTestSeriiM1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				przyciskTestSeriiM1ActionPerformed(evt, kolumna, zawartosc);
			}
		});
		
		
		malyPanel.add(przyciskHP);
		
		jPanel1.add(malyPanel);
	}

	void przyciskHActionPerformed(java.awt.event.ActionEvent evt, int kolumna, String zawartosc) {
		histAL.get(kolumna).frame.setVisible(true);
		histAL.get(kolumna).frame.setTitle("Histogram - " + zawartosc);
	}
	void przyciskHPActionPerformed(java.awt.event.ActionEvent evt, int kolumna, String zawartosc) {
		histpAL.get(kolumna).frame.setVisible(true);
		histpAL.get(kolumna).frame.setTitle("Histogram przedziałowy - " + zawartosc);
	}
	void przyciskTestSeriiM1ActionPerformed(java.awt.event.ActionEvent evt, int kolumna, String zawartosc) {

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
